apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: movies-circuit-breaker
  namespace: cinemaabyss
spec:
  host: movies-service
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN
    connectionPool:
      tcp:
        maxConnections: 200
      http:
        http1MaxPendingRequests: 100
        maxRequestsPerConnection: 100
        idleTimeout: 30s
    outlierDetection:
      consecutiveErrors: 3
      interval: 5s
      baseEjectionTime: 30s
      maxEjectionPercent: 50