apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ew0KICAgICJhdXRocyI6ICB7DQogICAgICAgICAgICAgICAgICAiZ2hjci5pbyI6ICB7DQogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgImF1dGgiOiAgImEzVnNZV0oxYUdFNloyaHdYMDl2V1ZWMVZVVlJUbE5DYzNBMmFrZFNhVE40WWt0eldtUktibVZzTVROYVRWRlhVZz09Ig0KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgfQ0KICAgICAgICAgICAgICB9DQp9DQo=
type: kubernetes.io/dockerconfigjson
